---
abstract: 'Scalar::In - replacement for smartmatch'
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
build_requires:
  Cwd: 0
  Test::Differences: 0.60
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Scalar-In
provides:
  Scalar::In:
    file: lib/Scalar/In.pm
    version: 0.002
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  Sub::Exporter: 0
  perl: 5.014
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
